name: Build and upload Windows app artifact

on:
  workflow_dispatch:
    inputs:
      buildBranch:
        description: 'kubeadmin ref/branch/tag'
        required: true
        default: 'main'

permissions:
  contents: read

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Download Helm 3.16.2
      run: |
        curl -L https://get.helm.sh/helm-v3.16.2-windows-amd64.tar.gz -o helm.tar.gz
        tar -zxvf helm.tar.gz
        mv darwin-amd64/helm backend/bin/helm
        rm -rf darwin-amd64 helm.tar.gz

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '22'  # Ensure this matches your project's Node.js version

    - name: Install and Build Frontend
      working-directory: frontend
      run: |
        npm install
        npm run build

    - name: Install Backend Dependencies
      working-directory: backend
      run: npm install

    - name: Install Desktop Dependencies
      working-directory: desktop
      run: npm install

    - name: Build Windows app
      working-directory: desktop
      env:
        ELECTRON_BUILDER_CACHE: '/tmp/electron-builder-cache'  # Override cache location
        ELECTRON_BUILDER_ALLOW_UNRESOLVED_DEPENDENCIES: 'true'  # Allow unresolved dependencies
        GH_TOKEN: ${{secrets.GITHUB_TOKEN}}
      run: npm run pack:win:publish