name: Build and upload docker image artifact

on:
  workflow_dispatch:
    inputs:
      tag:
        description: 'Select a tag to build'
        required: true
        default: 'v1.0.0'

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: lsword/kubeadmin

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Set up QEMU
      uses: docker/setup-qemu-action@49b3bc8e6bdd4a60e6116a5414239cba5943d3cf # v3.2.0
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@988b5a0280414f521da01fcc63a27aeeb4b104db # v3.6.1
    - name: Use Selected Tag
      run: |
        echo "BUILD_TAG=${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ github.event.inputs.tag }}" >> $GITHUB_ENV
    - name: checkout to build branch
      run: |
        git fetch origin
        git checkout ${{ env.BUILD_TAG }}
    - name: Log in to the Container registry
      uses: docker/login-action@465a07811f14bebb1938fbed4728c6a1ff8901fc # v2.2.0
      with:
        registry: ${{ env.REGISTRY }}
        username: ${{ github.actor }}
        password: ${{ github.token }}
    - name: Build and push Docker image
      uses: docker/build-push-action@0a97817b6ade9f46837855d676c4cca3a2471fc9 # v4.2.1
      with:
        context: .
        push: true
        pull: true
        platforms: linux/amd64
        tags: ${{ env.BUILD_TAG }}
        provenance: true
        cache-from: type=gha
        cache-to: type=gha,mode=max