name: Build and Release macOS App

on:
  release:
    types: [created]

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: lsword/kubeadmin

jobs:
  build-mac:
    runs-on: macos-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Download Helm 3.16.2
      run: |
        mkdir -p backend/bin
        curl -L https://get.helm.sh/helm-v3.16.2-darwin-amd64.tar.gz -o helm.tar.gz
        tar -zxvf helm.tar.gz
        mv darwin-amd64/helm backend/bin/helm
        rm -rf darwin-amd64 helm.tar.gz

    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '22'  # Ensure this matches your project's Node.js version

    - name: Install and Build Frontend
      working-directory: frontend
      run: |
        npm install
        npm run build

    - name: Install Backend Dependencies
      working-directory: backend
      run: npm install

    - name: Install Desktop Dependencies
      working-directory: desktop
      run: npm install

    - name: Build macOS app
      working-directory: desktop
      env:
        ELECTRON_BUILDER_CACHE: '/tmp/electron-builder-cache'  # Override cache location
        ELECTRON_BUILDER_ALLOW_UNRESOLVED_DEPENDENCIES: 'true'  # Allow unresolved dependencies
        GH_TOKEN: ${{secrets.GITHUB_TOKEN}}
      run: npm run pack:mac:publish

  build-win:
    runs-on: windows-latest
    permissions: write-all  
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Download Helm 3.16.2
      run: |
        curl -L https://get.helm.sh/helm-v3.16.2-windows-amd64.zip -o helm.zip 
        tar -xf helm.zip
        move windows-amd64\helm.exe backend\bin\helm.exe

    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '22'  # Ensure this matches your project's Node.js version

    - name: Install and Build Frontend
      working-directory: frontend
      run: |
        npm install
        npm run build

    - name: Install Backend Dependencies
      working-directory: backend
      run: npm install

    - name: Install Desktop Dependencies
      working-directory: desktop
      run: npm install

    - name: Build Windows app
      working-directory: desktop
      env:
        ELECTRON_BUILDER_CACHE: '/tmp/electron-builder-cache'  # Override cache location
        ELECTRON_BUILDER_ALLOW_UNRESOLVED_DEPENDENCIES: 'true'  # Allow unresolved dependencies
        GH_TOKEN: ${{secrets.GITHUB_TOKEN}}
      run: npm run pack:win:publish
